/*
Copyright (c) 2013, Atsushi Katagiri <akatagiri1@gmail.com>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice, 
  this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, 
  this list of conditions and the following disclaimer in the documentation 
  and/or other materials provided with the distribution.
* Neither the name of the <organization> nor the names of its contributors 
  may be used to endorse or promote products derived from this software 
  without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define BUFFSIZE	512

int main()
{
	char buff[BUFFSIZE];
	int comment = 1;
	int header = 1;
	int bitmap_top = 1;
	unsigned long line = 0;
	int characters = 256;
	int h_len = 16;
	int v_len = 32;
	char *token;
	int i;
	char *endptr;

	while (fgets(buff, BUFFSIZE, stdin)) {
		line++;
		if (line == 1) {
			printf("/* Generated by bdf2c */\n\n");
			printf("#include <stdint.h>\n\n");
		}
		if (comment) {
			if (header) {
				if (!strncmp(buff, "FONTBOUNDINGBOX", 15)) {
					token = strtok(buff, " ");
					token = strtok(NULL, " ");
					i = strtol(token, &endptr, 10);
					if (i > 0) {
						h_len = i;
					}
					token = strtok(NULL, " ");
					i = strtol(token, &endptr, 10);
					if (i > 0) {
						v_len = i;
					}
					printf("// ");
				} else if (!strncmp(buff, "CHARS ", 6)) {
					token = strtok(buff, " ");
					token = strtok(NULL, " ");
					i = strtol(token, &endptr, 10);
					if (i > 0) {
						characters = i;
					}
					printf("// ");
				} else if (!strncmp(buff, "STARTCHAR", 9)) {
					header = 0;
					printf("\nconst uint%d_t font[%d][%d] = {\n\t// ", h_len, characters, v_len);
				} else{
					printf("// ");
				}
			} else {
				if (!strncmp(buff, "ENDFONT", 7)) {
					printf("};\n// ");
				} else {
					printf("\t// ");
				}
			}
			fputs(buff, stdout);
			if (!strncmp(buff, "BITMAP", 6)) {
				printf("\t{\n");
				bitmap_top = 1;
				comment = 0;
			}
		} else {
			if (!strncmp(buff, "ENDCHAR", 7)) {
				printf("\t},\n\t// ");
				comment = 1;
				fputs(buff, stdout);
			} else {
				int j, k;
				char s[BUFFSIZE] = {0};
				size_t l;
				int d;

				strncpy(s, buff, strlen(buff) - 1);
				if (bitmap_top) {
					bitmap_top = 0;
					printf("\t\t ");
				} else {
					printf("\t\t,");
				}
				printf("0x%s\t//\t", s);

				l = strlen(s);
				d = strtol(s, &endptr, 16);
				if (!l) {
					fprintf(stderr, "Error");
					break;
				}
				for (j = l; j > 0; j--) {
					i = (d >> (j - 1) * 4) & 0xf;
					for (k = 3; k >= 0; k--) {
						if ((i >> k) & 0x1) {
							printf("%c", '#');
						} else {
							printf("%c", '.');
						}
					}
				}
				printf("\n");
			}
		}
	}

	return 0;
}
